{{- if .Values.global.enableSecurity }}
apiVersion: cert-manager.io/v1{{ if .Values.global.certificates.alphacrds }}alpha1{{ end }}
kind: Certificate
metadata:
  name: {{ template "seaweedfs.name" . }}-ca-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ template "seaweedfs.name" . }}-ca-cert
  commonName: "{{ template "seaweedfs.name" . }}-root-ca"
  isCA: true
  issuerRef:
    name: {{ template "seaweedfs.name" . }}-clusterissuer
    kind: ClusterIssuer
{{- end }}
