{{- if .Values.global.enableSecurity }}
apiVersion: cert-manager.io/v1{{ if .Values.global.certificates.alphacrds }}alpha1{{ end }}
kind: ClusterIssuer
metadata:
  name: {{ template "seaweedfs.name" . }}-clusterissuer
spec:
  selfSigned: {}
{{- end }}
