{{- if .Values.global.enableSecurity }}
apiVersion: cert-manager.io/v1{{ if .Values.global.certificates.alphacrds }}alpha1{{ end }}
kind: Certificate
metadata:
  name: {{ template "seaweedfs.name" . }}-master-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ template "seaweedfs.name" . }}-master-cert
  issuerRef:
    name: {{ template "seaweedfs.name" . }}-ca-issuer
    kind: Issuer
  commonName: {{ .Values.certificates.commonName }}
  subject:
    organizations:
    - "SeaweedFS CA"
  dnsNames:
    - '*.{{ .Release.Namespace }}'
    - '*.{{ .Release.Namespace }}.svc'
    - '*.{{ .Release.Namespace }}.svc.cluster.local'
    - '*.{{ template "seaweedfs.name" . }}-master'
    - '*.{{ template "seaweedfs.name" . }}-master.{{ .Release.Namespace }}'
    - '*.{{ template "seaweedfs.name" . }}-master.{{ .Release.Namespace }}.svc'
    - '*.{{ template "seaweedfs.name" . }}-master.{{ .Release.Namespace }}.svc.cluster.local'
{{- if .Values.certificates.ipAddresses }}
  ipAddresses:
    {{- range .Values.certificates.ipAddresses }}
    - {{ . }}
    {{- end }}
{{- end }}
  privateKey:
    algorithm: {{ .Values.certificates.keyAlgorithm }}
    size: {{ .Values.certificates.keySize }}
  duration: {{ .Values.certificates.duration }}
  renewBefore: {{ .Values.certificates.renewBefore }}
{{- end }}
