image:
  replicaCount: 1
  repository: ghcr.io/curie-data-factory/hdm
  tag: "2.3.0"
  pullPolicy: IfNotPresent
  name: hdm
  deployRegistry: false
  imagePullSecrets: registrysecret
  dataSecret: |-
    {"auths":{"registry.company.com":{"password":"","username":""}}}

service:
  type: ClusterIP
  targetPort: 80
  protocol: TCP

ingress:
  enabled: true
  hostnames:
  - hdm.company.com
  tls:
  - hosts:
    - hdm.company.com
    secretName: hdm

confLdap:
  key: "conf-ldap.json"
  data: |
    ""

confDb:
  key: "conf-db.json"
  data: |
    ""

confAppli:
  key: "conf-appli.json"
  data: |
    ""

confMail:
  key: "msmtprc"
  data: |
    ""
createTable:
  key: "create_tables.sql"
  data: |
    ""

################################################################################
## MYSQL

mysql:

  auth:
    rootPassword: rootpassword
    database: hdm
    username: hdm
    password: password

  primary:
    persistence:
      enabled: true
      size: 20Gi

################################################################################
## Kibana

kibana:
  elasticsearchHosts: http://hdm-deployement-elasticsearch-master:9200
  ingress:
    enabled: true
    # annotations:
    #   nginx.ingress.kubernetes.io/server-snippet: |
    #     more_set_headers "Content-Security-Policy: script-src https: 'unsafe-eval' 'unsafe-inline'; object-src 'none'";
    path: /
    hosts:
      - hdm-kibana.company.com
    tls:
      - hosts:
        - hdm-kibana.company.com
        secretName: hdm-kibana

################################################################################
## Elasticsearch

elasticsearch:
  clusterName: "hdm-deployement-elasticsearch"
  ingress:
    enabled: true
    path: /
    hosts:
      - hdm-elastic.company.com
    tls:
      - hosts:
        - hdm-elastic.company.com
        secretName: hdm-elastic
  persistence:
    enabled: false
