apiVersion: v2
description: Helm chart for QALITA Platform, a platform for managing and monitoring your data quality.
name: "qalita"
version: "1.7.0"
icon: https://avatars.githubusercontent.com/u/101010687?s=48&v=4
appVersion: "1.7.0"
home: https://qalita.io
kubeVersion: ">= 1.24.0-0"
type: application
keywords:
  - cloud-native
  - data-quality
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.8.2
    condition: postgresql.enabled
  - name: redis
    repository: https://deps.truecharts.org
    version: 11.1.4
    condition: redis.enabled
  - name: seaweedfs
    repository: https://seaweedfs.github.io/seaweedfs/helm
    version: 3.55.0
    condition: seaweedfs.enabled
maintainers:
  - name: qalita
    email: contact@qalita.io
    url: https://qalita.io
