apiVersion: v2
description: Helm chart for QALITA Platform, a platform for managing and monitoring your data quality.
name: "qalita"
version: "2.2.0"
icon: https://avatars.githubusercontent.com/u/101010687?s=48&v=4
appVersion: "2.2.0"
home: https://qalita.io
kubeVersion: ">= 1.24.0-0"
type: application
keywords:
  - cloud-native
  - data-quality
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.12.10
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.16.1
    condition: redis.enabled
  - name: seaweedfs
    repository: https://seaweedfs.github.io/seaweedfs/helm
    version: 4.0.380
    condition: seaweedfs.enabled
maintainers:
  - name: qalita
    email: contact@qalita.io
    url: https://qalita.io
