apiVersion: v2
name: qalita
description: Qalita
type: application
appVersion: 0.0.0
version: 1.0.0
home: https://github.com/qalita-io/helm/tree/main/charts/Qalita
icon: https://qalita.io/wp-content/uploads/2022/05/logo-1024x388.png
sources:
  - https://qalita.io/
maintainers:
  - name: armandleopold
    email: armand.leopold@qalita.io
keywords:
  - qalita
