apiVersion: v2
description: Helm chart for QALITA Platform
name: qalita
version: "1.0.0"
icon: https://avatars.githubusercontent.com/u/101010687?s=48&v=4
appVersion: "1.0.0"
home: https://qalita.io
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 12.5.8
  - name: seaweedfs
    repository: https://seaweedfs.github.io/seaweedfs/helm
    version: 3.53.0
maintainers:
  - name: Qalita
    email: contact@qalita.io
    url: https://qalita.io
