cluster:
  issuer: letsencrypt-prod
  domain: example.com
  name: local

dockerregistry:
  enabled: true
  dataSecret: |-
    {"auths":{"<registry-url>":{"password":"<password>","username":"<username>"}}}

frontend:
  image:
    repository: qalita.azurecr.io/qalita/frontend
    tag: "1.6.1"
    pullPolicy: IfNotPresent

  replicaCount: 1

  telemetryDisabled: "1"
  webPackPolling: "false"
  mode: "production"

  service:
    type: ClusterIP
    targetPort: "3000"
    protocol: TCP

  ingress:
    enabled: true
    tls:
      enabled: true

  deployment:
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"

    extraEnv:

doc:
  image:
    repository: qalita.azurecr.io/qalita/doc
    tag: "1.6.0"
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    type: ClusterIP
    targetPort: "80"
    protocol: TCP

  ingress:
    enabled: true
    tls:
      enabled: true

  deployment:
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"

backend:
  image:
    repository: qalita.azurecr.io/qalita/backend
    tag: "1.6.1"
    pullPolicy: IfNotPresent

  replicaCount: 1

  organization:
    name: "local"

  tokenExpireMinutes: 240
  mode: "PROD"
  iniSleep: "3"

  adminUsername: "admin"
  adminPassword:
  secretKey:
  secretKeyAlgorithm: "HS256"

  s3:
    url: "http://seaweedfs-s3:8333"
    secretName: seaweedfs-s3-secret
    admin_access_key_id:
    admin_secret_access_key:
    read_access_key_id:
    read_secret_access_key:

  api:
    port: "3080"
    host: "0.0.0.0"
    worker: 4

  service:
    type: ClusterIP
    targetPort: "3080"
    protocol: TCP

  ingress:
    enabled: true
    tls:
      enabled: true

  deployment:
    resources:
      requests:
        memory: "1024Mi"
        cpu: "200m"

    extraEnv:

agent:
  enabled: false
  name: "local-agent"
  mode: "worker"
  token: "changeme"

  image:
    repository: qalita/agent
    tag: "1.6.2"
    pullPolicy: IfNotPresent

  replicaCount: 1

  pvc:
    enabled: false
    storageSize: "10Gi"

  initscript: |
    #!/bin/bash
    echo "Hello World"

  deployment:
    resources:
      requests:
        memory: "256Mi"
        cpu: "200m"

    extraEnv:

postgresql:
  enabled: true
  image:
    tag: "15.3.0"

  global:
    postgresql:
      auth:
        database: qalitadb
        username: qalita
        password:

  primary:
    persistence:
      size: 8Gi

  backup:
    enabled: false
    cronjob:
      storage:
        resourcePolicy: "keep"

redis:
  enabled: true
  volumeClaimTemplates:
    data:
      enabled: false

seaweedfs:
  enabled: true
  global:
    createClusterRole: true
    imageName: chrislusf/seaweedfs

  filer:
    resources: |
      requests:
        memory: "256Mi"
        cpu: "50m"

  volume:
    data:
      type: "persistentVolumeClaim"
      size: "21Gi"

    resources: |
      requests:
        memory: "100Mi"
        cpu: "50m"

  master:
    resources: |
      requests:
        memory: "64Mi"
        cpu: "50m"

helmsync:
  enabled: false
  image:
    repository: alpine/helm

  kubeconfig: |-
    apiVersion: v1
    kind: Config
    clusters:
    - name: "<kubernetes_cluster_name>"
      cluster:
        server: "<kubernetes_api_server_url>"
    users:
    - name: "<kubernetes_cluster_name>-user"
      user:
        token: "<kubernetes_cluster_token>"
    contexts:
    - name: "<kubernetes_cluster_name>-context"
      context:
        user: "<kubernetes_cluster_name>-user"
        cluster: "<kubernetes_cluster_name>"
    current-context: "<kubernetes_cluster_name>-context"

  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
