apiVersion: v2
name: apisix
description: Apache APISIX
type: application
appVersion: 3.1.1
version: 1.1.2
home: https://github.com/qalita-io/helm/tree/main/charts/apisix
icon: https://apisix.apache.org/img/logo.png
sources:
  - https://apisix.apache.org/
maintainers:
  - name: armandleopold
    email: armand.leopold@qalita.io
keywords:
  - apisix
dependencies:
  - name: apisix
    repository: https://charts.apiseven.com
    version: 1.1.1
