apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-doc"
  labels:
    app: "{{ .Release.Name }}-doc"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{ include "qalita.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.doc.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-doc"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-doc"
        release: {{ .Release.Name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - name: "doc"
        image: "{{ .Values.doc.image.repository }}:{{ .Values.doc.image.tag }}"
        imagePullPolicy: {{ .Values.doc.image.pullPolicy }}
{{- if .Values.doc.deployment.env }}
{{ toYaml .Values.doc.deployment.env | indent 10 }}
{{- end }}
        ports:
        - containerPort: {{ .Values.doc.service.targetPort }}
          name: {{ .Values.doc.service.targetPort }}{{ .Values.doc.service.protocol | lower }}
          protocol: {{ .Values.doc.service.protocol }}
{{- if .Values.doc.deployment.resources }}
        resources:
{{ toYaml .Values.doc.deployment.resources | indent 10 }}
{{- end }}
      {{- if .Values.dockerregistry.enabled }}
      imagePullSecrets:
      - name: qalita-platform-dockerregistry
      {{- end }}
