{{ if .Values.doc.enabled }}
{{- if .Values.doc.ingress.enabled -}}
{{- $serviceName := print .Release.Name "-doc-service" }}
{{- $servicePort := print .Values.doc.service.targetPort .Values.doc.service.protocol | lower -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-doc-ingress"
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.cluster.issuer }}
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "false"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    app: "{{ .Release.Name }}-doc"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.doc.ingress.annotations }}
  annotations:
{{ toYaml .Values.doc.ingress.annotations | indent 4 }}
{{- end }}
spec:
{{- if .Values.doc.ingress.tls.enabled }}
  tls:
  - hosts:
    - doc.{{ .Values.cluster.domain }}
    secretName: doc-cert
{{- end }}
  rules:
  - host: doc.{{ .Values.cluster.domain }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $serviceName }}
            port:
              name: {{ $servicePort }}
{{ end -}}
{{ end }}