{{ if .Values.helmsync.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helmsync
  labels:
    app: "{{ .Release.Name }}-helmsync"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-helmsync"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-helmsync"
        release: {{ .Release.Name }}
    spec:
      containers:
        - args:
            - 'infinity'
          command:
            - sleep
          env:
            - name: KUBECONFIG
              value: /root/kubeconfig/kubeconfig.yaml
          image: {{ .Values.helmsync.image.repository }}
          name: helmsync
          volumeMounts:
          - mountPath: /root/kubeconfig
            name: "helmsync-kubeconfig"
            readOnly: true
{{- if .Values.helmsync.resources }}
          resources:
{{ toYaml .Values.helmsync.resources | indent 12 }}
{{- end }}
      volumes:
        - name: "helmsync-kubeconfig"
          secret:
            defaultMode: 420
            secretName: "helmsync-kubeconfig"
{{- end }}
