apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-qalita-secret"
data:
  adminPassword: {{ default (randAlphaNum 25 | b64enc) .Values.backend.adminPassword | b64enc }}
  secretKey: {{ default (randAlphaNum 512 | b64enc) .Values.backend.secretKey | b64enc }}
