apiVersion: v1
data:
  adminPassword: {{ .Values.backend.adminPassword | b64enc }}
  secretKey: {{ .Values.backend.secretKey | b64enc }}
kind: Secret
metadata:
  name: "{{ .Release.Name }}-qalita-secret"
