{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "qalita-rediscreds"
data:
  redis-password: {{ default (randAlphaNum 25 | b64enc) .Values.redis.password | b64enc }}
{{- end }}
