{{- if .Values.dockerregistry.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: "qalita-platform-dockerregistry"
data:
  .dockerconfigjson: {{ 
    printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" 
      .Values.licenseUrl 
      .Values.licenseUser 
      .Values.licenseKey 
      (printf "%s:%s" .Values.licenseUser .Values.licenseKey | b64enc)
    | b64enc 
  }}
{{- end }}