{{- if .Values.dockerregistry.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: "{{ .Release.Name }}-dockerregistry"
data:
  .dockerconfigjson: {{ .Values.dockerregistry.dataSecret | b64enc }}
{{- end }}