{{- if .Values.dockerregistry.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: "{{ .Release.Name }}-dockerregistry"
dataString:
  .dockerconfigjson: {"auths":{"{{ .Values.licenseUrl }}":{"password":"{{ .Values.licenseKey }}","username":"{{ .Values.licenseUser }}"}}}
{{- end }}