{{- if not .Values.seaweedfs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "s3-secret"
data:
  admin_access_key_id: {{ .Values.backend.s3.admin_access_key_id | b64enc }}
  admin_secret_access_key: {{ .Values.backend.s3.admin_secret_access_key | b64enc }}
  read_access_key_id: {{ .Values.backend.s3.read_access_key_id | b64enc }}
  read_secret_access_key: {{ .Values.backend.s3.read_secret_access_key | b64enc }}
{{- end }}