{{- if .Values.seaweedfs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-s3-secret
data:
  admin_access_key_id: {{ .Values.backend.s3.admin_access_key_id | b64enc }}
  admin_secret_access_key: {{ .Values.backend.s3.admin_secret_access_key | b64enc }}
  read_access_key_id: {{ .Values.backend.s3.read_access_key_id | b64enc }}
  read_secret_access_key: {{ .Values.backend.s3.read_secret_access_key | b64enc }}
  seaweedfs_s3_config: '{"identities":[{"name":"anvAdmin","credentials":[{"accessKey":"{{ .Values.backend.s3.admin_secret_access_key }}","secretKey":"{{ .Values.backend.s3.admin_secret_access_key }}"}],"actions":["Admin","Read","Write"]},{"name":"anvReadOnly","credentials":[{"accessKey":"{{ .Values.backend.s3.read_access_key_id }}","secretKey":"{{ .Values.backend.s3.read_secret_access_key }}"}],"actions":["Read"]}]}'
{{- end }}