{{- if .Values.seaweedfs.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: seaweedfs-s3-secret
stringData:
  admin_access_key_id: '{{ .Values.backend.s3.admin_access_key_id }}'
  admin_secret_access_key: '{{ .Values.backend.s3.admin_secret_access_key }}'
  read_access_key_id: '{{ .Values.backend.s3.read_access_key_id }}'
  read_secret_access_key: '{{ .Values.backend.s3.read_secret_access_key }}'
  seaweedfs_s3_config: '{"identities":[{"name":"anvAdmin","credentials":[{"accessKey":"{{.Values.backend.s3.admin_access_key_id }}","secretKey":"{{.Values.backend.s3.admin_secret_access_key }}"}],"actions":["Admin","Read","Write","List","Tagging"]},{"name":"anvReadOnly","credentials":[{"accessKey":"{{.Values.backend.s3.read_access_key_id }}","secretKey":"{{.Values.backend.s3.read_secret_access_key }}"}],"actions":["Read"]}]}'
{{- end }}