{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ .Values.image.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ .Values.image.name }}-docker-release"
{{- with .Values.ingress.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.urldockerrelease }}
      http:
        paths:
          - path: {{ .Values.ingress.urlDockerReleasePath }}
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-{{ .Values.image.name }}"
                port:
                  number: 8083
  tls:
  - hosts:
    - {{ .Values.ingress.urldockerrelease }}
    secretName: {{ .Values.ingress.urldockerreleasename }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ .Values.image.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ .Values.image.name }}-docker-snapshot"
{{- with .Values.ingress.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.urldockersnapshot }}
      http:
        paths:
          - path: {{ .Values.ingress.urlDockerSnapshotPath }}
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-{{ .Values.image.name }}"
                port:
                  number: 8082
  tls:
  - hosts:
    - {{ .Values.ingress.urldockersnapshot }}
    secretName: {{ .Values.ingress.urldockersnapshotname }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: {{ .Values.image.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: "{{ .Release.Name }}-{{ .Values.image.name }}"
{{- with .Values.ingress.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end }}
  rules:
    - host: "{{ .Values.ingress.url }}"
      http:
        paths:
          - path: {{ .Values.ingress.urlPath }}
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-{{ .Values.image.name }}"
                port:
                  number: 8081
{{- end -}}
