apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.image.name }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
    - name: dockersnapshot
      port: 8082
      protocol: TCP
      targetPort: 8082
    - name: dockerrelease
      port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: "{{ .Release.Name }}-{{ .Values.image.name }}"
    release: {{ .Release.Name }}
