on: [push, pull_request]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@v4.0.0
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
