name: Release Charts

on:
  push:
    branches:
      - master
    paths:
      - "charts/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.5.2

      - name: Set up Helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami/
          helm repo add elastic https://helm.elastic.co

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.0
        with:
          charts_repo_url: https://qalita-io.github.io/helm
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
