name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set up Helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add elastic https://helm.elastic.co
          helm repo add apisix  https://charts.apiseven.com
          helm repo add argo    https://argoproj.github.io/argo-helm
          helm repo add vault   https://helm.releases.hashicorp.com
          helm repo add jetstack https://charts.jetstack.io
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          charts_repo_url: https://helm.qalita.io
        env:
          CR_TOKEN: "${{ secrets.CR_TOKEN }}"
